name = "animestream-addon"
main = "worker-github.js"
compatibility_date = "2024-01-01"
# account_id configured via wrangler login

[vars]
ENVIRONMENT = "production"

# KV namespace for storing user scrobbling tokens
[[kv_namespaces]]
binding = "USER_TOKENS"
id = "928dc36173b84dd8bee471aecaf69a8d"
    